import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '../src/styles/main.scss'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const roboto = Roboto({
   subsets: ['latin'],
   weight: ['400', '700'],
   display: 'swap',
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`${roboto.className} `}>
            <AntdRegistry>{children}</AntdRegistry>
         </body>
      </html>
   )
}
